# Use Python 3.9 Slim
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --default-timeout=10000 --no-cache-dir -r requirements.txt

# Copy the Dashboard code
COPY dashboard/ dashboard/

# Expose Streamlit port
EXPOSE 8501

# Start Streamlit
# We point to the specific file location
CMD ["streamlit", "run", "dashboard/frontend.py", "--server.port=8501", "--server.address=0.0.0.0"]